spring.application.name=rbpo2
server.port=8443

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.access.expiration=900000
jwt.refresh.expiration.days=7

app.admin.username=${ADMIN_USERNAME}
app.admin.password=${ADMIN_PASSWORD}
app.admin.email=${ADMIN_EMAIL}

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${KEYSTORE_PASSWORD}
server.ssl.key-alias=laba6_key

signature.key-store-path=classpath:keystore.p12
signature.key-store-type=PKCS12
signature.key-store-password=${KEYSTORE_PASSWORD}
signature.key-alias=laba6_key
signature.key-password=${SIGNATURE_KEY_PASSWORD}
signature.algorithm=SHA256withRSA
signature.public-certificate-base64=${LICENSE_PUBLIC_CERT_BASE64}