spring.application.name=rbpo2
server.port=8443

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:rbpo2;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

jwt.secret=${JWT_SECRET}
jwt.access.expiration=900000
jwt.refresh.expiration.days=7

app.admin.username=${ADMIN_USERNAME}
app.admin.password=${ADMIN_PASSWORD}
app.admin.email=${ADMIN_EMAIL}

server.ssl.enabled=true
server.ssl.key-store=file:certs/keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${KEYSTORE_PASSWORD}
server.ssl.key-password=${KEYSTORE_PASSWORD}
server.ssl.key-alias=laba6_key

signature.key-store-path=file:certs/signing-keystore.p12
signature.key-store-type=PKCS12
signature.key-store-password=${SIGNATURE_KEY_PASSWORD:${KEYSTORE_PASSWORD}}
signature.key-alias=ticket_signing
signature.key-password=${SIGNATURE_KEY_PASSWORD:${KEYSTORE_PASSWORD}}
signature.algorithm=SHA256withRSA
signature.public-certificate-base64=${PUBLIC_KEY_CERT:}